version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: nebenkosten-energierechner
    main: ./cmd/nebenkosten-energierechner
    binary: nebenkosten-energierechner
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.buildDate={{.Date}}
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "7"

archives:
  - id: nebenkosten-energierechner
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^test:"
      - "^chore:"

release:
  github:
    owner: larknafets
    name: nebenkosten-energierechner
